# Site settings
title: The Changing Workplace
description: The Changing Workplace | We are an industry-leading provider of web-based CAFM software solutions for Corporate Real Estate and Facilities groups.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://changingworkplace.com" # the base hostname & protocol for your site
port: 8500

# Build settings
markdown: kramdown
highligher: rouge

#Plugins

prose:
  rooturl: '_posts'
  siteurl: 'http://site-cwp.github.io/'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "select"
          label: "Post layout"
          placeholder: ""
          options:
            - name: "Product"
              value: "products"
            - name: "Post"
              value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "summary"
        field:
          element: "text"
          label: "Summary"
          value: ""
      - name: "direct_link"
        field:
          element: "select"
          label: "Direct to download (only for resources - like Factsheets)"
          options:
            - name: "Yes"
            - value: "yes"
            - name: "No"
            - value: "no"
      - name: "contains_pdf"
        field:
          element: "select"
          label: "Have you attached a PDF? (only for resources. PDF must be placed inside the pdf folder with the same title as this post)"
          options:
            - name: "Yes"
            - value: "yes"
            - name: "No"
            - value: "no"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Select categories"
          placeholder: "E.g. resource, white paper"
          options:
            - name: "Products"
              value: "products"
            - name: "Featured products"
              value: "featured"
            - name: "Services"
              value: "services"
            - name: "Featured service"
              value: "services-featured"
            - name: "Jobs"
              value: "job"
            - name: "News"
              value: "news"
            - name: "Resources"
              value: "resources"
            - name: "Casestudy"
              value: "casestudy"
            - name: "Whitepaper"
              value: "whitepaper"
            - name: "Factsheet"
              value: "factsheet"
      - name: "tags"
        field:
          element: "text"
          label: "Post tags"
          placeholder: "For SEO. Seperate each by comma"
          value: ""
# Categories
categories: 
 - news
 - products
 - services
 - products
 - resources
 - featured
 - casestudy
 - whitepaper
 - factsheet

#Permalinks
permalink: /:categories/:title
